import {createSyncControls} from './sync-controls.mjs?v=sync2';
import {sportIcon,icon} from './lib/icons.mjs';
import {createPhoneApp} from './phone-app.mjs?v=icons1';
import {createMobility} from './mobility-view.mjs?v=mobility-log1';
import {setupJournal,paintJournal} from './journal-view.mjs?v=icons1';
setupJournal();
const mobility=createMobility({onSave:async body=>{if(!owner)throw new Error('Sign in to log mobility.');await api('mobility_complete',body);await refresh();}});
const phoneApp=createPhoneApp({onRefresh:()=>refresh()});
let liveWorkoutsLoaded=false;
const preview=location.hostname==='127.0.0.1' && new URLSearchParams(location.search).has('preview');
import {shift,weekReview,enduranceCompare,repeatNote} from './lib/review.mjs?v=today4';
import {createMuscleMap} from './muscle-view.mjs?v=map3';
import {dateStart, progressWeeks, filterWorkouts, bestEfforts, clockTime, SANTA_CRUZ} from './lib/progress.mjs';
import { parseWorkoutNote } from './lib/note-parser.mjs?v=mobile2';
import { setupPush } from './push.mjs';
import { number, localDate, completed, totals, weekly, strengthHistory, trainingPeaksCsv, validateWorkout } from './lib/fitness.mjs?v=mobile2';
const $ = id => document.getElementById(id), C = window.FITNESS_CONFIG;
const fmt = (n, d=0) => number(n).toLocaleString(undefined,{maximumFractionDigits:d});
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty = (date, options={month:'short',day:'numeric'}) => new Date(date+'T12:00:00').toLocaleDateString('en-US',options);
const status = (id,text,error=false) => { $(id).textContent=text; $(id).className='form-status '+(error?'error':'success'); };
const auth = !preview && window.supabase?.createClient(C.supabaseUrl,C.publishableKey);
let session = null, owner = false, rows = window.WORKOUTS || [], checkins = [], connections = {}, active='All', visible=15, editing=null, importRows=[], refreshVersion=0, parsedNote=null, notificationPending=new URLSearchParams(location.search).get('log')==='strength';
let publicPlans=[];
async function api(action, body={}) {
 if(preview){if(action!=="public")throw new Error("This design preview is read-only.");return (await fetch("/preview-data.json")).json();}
  const url=C.apiUrl+(action==='public'?'?resource=public':action==='private'?'?resource=private':'');
  const r=await fetch(url,{method:['public','private'].includes(action)?'GET':'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{})},...(!['public','private'].includes(action)?{body:JSON.stringify({action,...body})}:{}),signal:AbortSignal.timeout(45000)});
  const data=await r.json(); if(!r.ok) throw new Error(data.error || 'Could not load the log.'); return data;
}
const syncControls=createSyncControls({api,refresh,owner:()=>owner});
function rangeRows() {
 const range=$('range').value, today=localDate(); if(range==='all') return rows.filter(r=>r.date<=today);
 const d=new Date(today+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()-Number(range)+1);
 const start=range==='year'?today.slice(0,4)+'-01-01':d.toISOString().slice(0,10);
 return rows.filter(r=>r.date>=start && r.date<=today);
}
function paintProgress() {
 const t=totals(rangeRows()); $('stats').innerHTML=[['sessions',t.sessions,'','Sessions logged'],['hours',t.hours,'hr','Training time'],['bike',t.bike,'mi','On the bike'],['run',t.run,'mi','Run & walk'],['swim',t.swim,'yd','In the water'],['strength',t.strength,'','Strength sessions']].map(([key,value,unit,label])=>`<div class="stat"><div class="stat-value">${fmt(value,['hours','bike','run'].includes(key)?1:0)} <small>${unit}</small></div><div class="stat-label">${label}</div></div>`).join('');
 const weeks=progressWeeks(rows,$('range').value), max=Math.max(1,...weeks.map(w=>w.endurance+w.strength)); $('chartScale').textContent=fmt(max,1)+' hr';
 $('volumeChart').innerHTML=weeks.map(w=>{const total=w.endurance+w.strength; return `<div class="bar-wrap" tabindex="0" role="img" aria-label="Week of ${pretty(w.date)}: ${fmt(total,1)} hours, ${w.sessions} sessions" title="Week of ${pretty(w.date)} · ${fmt(total,1)} hr · ${w.sessions} sessions"><div class="bar-label">${total?fmt(total,1):''}</div><div class="bar-stack" style="height:${total/max*83}%"><div class="bar-part strength" style="height:${total?w.strength/total*100:0}%"></div><div class="bar-part endurance" style="height:${total?w.endurance/total*100:0}%"></div></div></div>`;}).join('');
 $('chartPeriod').textContent=$('range').selectedOptions[0].textContent.toUpperCase()+' · WEEKLY HOURS';$('volumeChart').style.setProperty('--week-count',weeks.length);$('chartStart').textContent=pretty(dateStart($('range').value,localDate(),completed(rows))); $('chartEnd').textContent=pretty(weeks.at(-1).date);
 const recent=completed(rangeRows()),rt=totals(recent);
 $('recentStats').innerHTML=[['Sessions',rt.sessions],['Hours logged',fmt(rt.hours,1)],['Strength sessions',rt.strength]].map(([label,value])=>`<div class="recent-row"><span>${label}</span><strong>${value}</strong></div>`).join('');
 $('recentNote').textContent=recent.length?'Latest logged session: '+pretty(recent.map(r=>r.date).sort().at(-1))+'.':'No completed sessions in this period.';
}
function paintStrength() {
 const names=[...new Set(completed(rangeRows()).flatMap(r=>(r.exercises||[]).map(e=>e.name)))].sort();
 const selected=$('exerciseSelect').value; $('exerciseSelect').innerHTML=names.length?names.map(n=>`<option>${esc(n)}</option>`).join(''):'<option>No sets logged yet</option>';
 if(names.includes(selected)) $('exerciseSelect').value=selected; $('exerciseSelect').disabled=!names.length;
 $('strengthSummary').innerHTML=`<div class="metric-pills"><span>${totals(rangeRows()).strength} strength sessions recorded</span><span>${names.length} exercises with sets</span></div>`;
 paintLift();
}
function paintLift() {

 const history=strengthHistory(rangeRows(),$('exerciseSelect').value);
 if(!history.length){$('strengthChart').innerHTML='<div class="empty"><span class="empty-icon">↔</span>Your earlier strength notes are preserved.<br>Log sets and reps to start tracking lift progression.</div>';return;}
 $('strengthChart').innerHTML='<table class="strength-history"><thead><tr><th>DATE</th><th>TOP LOAD</th><th>WORK VOLUME</th><th>EST. 1RM*</th></tr></thead><tbody>'+history.slice(-8).map(h=>`<tr><td>${pretty(h.date)}</td><td>${h.unit==='bodyweight'?'Bodyweight':fmt(h.best,1)+' '+h.unit}</td><td>${h.seconds?fmt(h.seconds)+' sec'+(h.volume?' + ':''):''}${h.volume||!h.seconds?fmt(h.volume)+' '+(h.unit==='bodyweight'?'':h.unit+' × reps'):''}</td><td>${h.estimatedMax?fmt(h.estimatedMax,1)+' '+h.unit:'—'}</td></tr>`).join('')+'</tbody></table>';
 $('strengthChart').title='Estimated 1RM uses Epley on working sets of 1–10 reps. It is not a measured maximum.';
}
function paintTabs() {
 const types=['All',...new Set(completed(rows).map(r=>r.type))]; if(totals(rangeRows()).strength && !types.includes('Strength'))types.push('Strength');
 $('typeTabs').innerHTML=types.map(t=>`<button class="tab ${t===active?'active':''}" aria-pressed="${t===active}">${esc(t)}</button>`).join('');
 [...$('typeTabs').children].forEach(b=>b.onclick=()=>{active=b.textContent;visible=15;paintTabs();paintLog();});
}
function workoutMeta(r) {
 return [r.duration_hours?fmt(r.duration_hours*60,1)+' min':null,r.bike_miles?fmt(r.bike_miles,1)+' mi bike':null,r.run_miles?fmt(r.run_miles,1)+' mi run / walk':null,r.swim_yards?fmt(r.swim_yards)+' yd swim':null,r.strength && r.type!=='Strength'?'+ strength':null,owner && r.rpe?'RPE '+r.rpe:null].filter(Boolean).join(' · ') || 'Duration not recorded';
}
function paintLog() {
 const filtered=filterWorkouts(rangeRows(),{sport:active,status:owner?$('logStatus').value:'completed',start:$('logFrom').value,end:$('logTo').value,term:$('search').value,sort:$('logSort').value,privateDetails:owner});
 $('logCount').textContent=Math.min(visible,filtered.length)+' of '+filtered.length+' matching workouts';$('showAll').hidden=filtered.length<=visible;
 $('workoutList').innerHTML=filtered.slice(0,visible).map(r=>`<article class="workout-row"><div class="workout-date"><b>${pretty(r.date)}</b>${r.date.slice(0,4)}</div><div class="sport-icon ${r.type==='Strength'?'strength':''}" aria-hidden="true">${sportIcon(r.type)}</div><div><h3>${esc(r.title)}${r.status==='planned'?' <span class="badge">'+(r.date<localDate()?'No actuals recorded':'Planned')+'</span>':r.status==='skipped'?' <span class="badge">Skipped</span>':''}</h3><div class="workout-meta">${esc(workoutMeta(r))}</div></div><div class="workout-actions"><span class="workout-source">${esc(r.source || 'Manual')}</span>${owner?`<button class="text-button edit-workout" data-id="${esc(r.id)}">Edit ↗</button>`:''}</div>${owner||(r.exercises||[]).length||(r.mobility_stretches||[]).length?`<details class="private-details"><summary>${r.type==='Mobility'?'Completed stretches':owner?'Notes & lifting sets':'Lifting sets'}</summary><p>${owner?(esc([r.summary,r.details,r.private_notes].filter(Boolean).join('\n')) || 'No notes recorded.'):''}</p>${(r.mobility_stretches||[]).map(s=>`<p><strong>${esc(s.name)}</strong> · ${esc(s.seconds_per_side)} sec${s.sides===2?' each side':''}</p>`).join('')}${(r.exercises||[]).map(e=>`<strong>${esc(e.name)} · ${esc(e.unit)}</strong><table class="sets-read"><tr><th>Set</th><th>Reps / time</th><th>Load</th><th>Effort</th></tr>${e.sets.map((s,i)=>`<tr><td>${i+1}${s.kind==='warmup'?' · warm-up':''}</td><td>${s.seconds!=null?esc(s.seconds)+' sec':esc(s.reps)}</td><td>${e.unit==='bodyweight'?'BW':esc(s.weight)+' '+esc(e.unit)}</td><td>${owner?(s.rpe||'—'):'—'}</td></tr>`).join('')}</table>`).join('')}</details>`:''}</article>`).join('')||'<div class="empty">No workouts match this view.</div>';
 $('loadMore').hidden=filtered.length<=visible; document.querySelectorAll('.edit-workout').forEach(b=>b.onclick=()=>openWorkout(rows.find(r=>r.id===b.dataset.id)));
}
function paintPlans() {
 const planned=rows.filter(r=>r.status==='planned' && r.date>=localDate()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,12);
 $('plannedList').innerHTML=planned.length?planned.map(r=>`<article class="plan-card"><div class="eyebrow">${pretty(r.date)} · ${esc(r.type)}</div><h3>${esc(r.title)}</h3><p class="fine">${r.planned_duration_hours?fmt(r.planned_duration_hours*60)+' min prescribed · ':''}${esc(r.source)}</p><button class="button outline small complete-plan" data-id="${r.id}">Log actual workout ↗</button></article>`).join(''):'<p class="muted">Connect your TrainingPeaks calendar below, or add a prescription. Only verified planned strength days will trigger a lifting check-in.</p>';
 document.querySelectorAll('.complete-plan').forEach(b=>b.onclick=()=>openWorkout({...rows.find(r=>r.id===b.dataset.id),status:'completed'}));
}
function paintRecovery() {
 $('recoveryList').innerHTML=checkins.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(({date,data:r})=>`<div class="recovery-row"><strong>${pretty(date)}</strong>${[['sleep_hours','h sleep'],['energy','/5 energy'],['soreness','/5 soreness'],['weight',' '+(r.weight_unit||'lb')],['resting_hr',' bpm resting'],['hrv',' ms HRV']].filter(([k])=>r[k]!=null).map(([k,u])=>'<span>'+esc(r[k])+u+'</span>').join('')}</div>`).join('')||'<p class="fine">No recovery check-ins yet. Log only the metrics you find useful.</p>';
}
function paintEndurance() {
 const sport=$('enduranceSport').value, sessions=completed(rows).filter(r=>r.type===sport && r.source!=='Notes' && r.history_quality!=='reconstructed').sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10);
 const pace=r=>{const distance=sport==='Run'?r.run_miles:sport==='Swim'?r.swim_yards/100:0;if(!distance||!r.duration_hours)return '—';const seconds=Math.round(r.duration_hours*3600/distance);return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')+(sport==='Swim'?' /100 yd':' /mi');};
 $('enduranceHistory').innerHTML=sessions.length?'<div class="table-scroll"><table class="strength-history"><thead><tr><th>DATE</th><th>'+ (sport==='Bike'?'AVG POWER':'SESSION PACE') +'</th><th>AVG HR</th><th>EFFORT</th></tr></thead><tbody>'+sessions.map(r=>'<tr><td>'+pretty(r.date)+'</td><td>'+(sport==='Bike'?(r.average_power?fmt(r.average_power)+' W':'—'):pace(r))+'</td><td>'+(r.average_hr?fmt(r.average_hr)+' bpm':'—')+'</td><td>'+(r.rpe?'RPE '+r.rpe:'—')+'</td></tr>').join('')+'</tbody></table></div>':'<p class="muted">Log an endurance session with measured duration and distance to start comparing performance.</p>';
}
function paintConnections() {
 $('calendarBadge').textContent=connections.calendar?'Connected':'Not connected';
 const h=connections.hosted;$('hostedStatus').textContent=h?((h.enabled?'Enabled':'Paused / awaiting setup')+' · '+h.status+(h.last_success_at?' · Last successful check: '+new Date(h.last_success_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})+' Pacific.':' · No successful hosted check yet.')+(h.reviews?.length?' '+h.reviews.length+' activity matches need review.':'')):'Not configured.';const sync=connections.last_sync;$('syncStatus').textContent=sync?'Last sync: '+new Date(sync.at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})+' Pacific. '+(sync.calendar_error||'')+' '+(sync.activities_error||'')+(sync.calendar==='connected'?' '+sync.planned+' upcoming prescriptions; '+sync.strength_planned+' identified as strength.':''):'Connect a source to enable hourly background syncing.';
}
function render() {
 syncControls.paint(connections.dispatch);$('signIn').textContent=session?'Sign out':'Sign in'; $('modeLabel').textContent=session?'SIGNED IN':'PUBLIC PROGRESS';$('ownerBadge').hidden=!owner;if(!owner){$('runnerKey').value='';$('runnerKey').hidden=true;$('copyRunner').hidden=true;}$('signOut').hidden=!session;if(notificationPending&&!session&&!$('loginDialog').open)$('loginDialog').showModal();
 document.querySelectorAll('.private-section').forEach(el=>el.hidden=!owner);paintJournal(rows,publicPlans);mobility.paint(rows,liveWorkoutsLoaded,owner);paintToday();paintReview();if(owner)paintBenchmarks();paintProgress();paintBest();muscleMap.paint();paintStrength();paintTabs();paintLog();phoneApp.paint(rows,owner,liveWorkoutsLoaded);if(owner){paintPlans();paintRecovery();paintEndurance();paintConnections();push.refresh();if(notificationPending){notificationPending=false;setTimeout(openNotificationWorkout,0);}}
}
async function refresh() {
 const version=++refreshVersion, token=session?.access_token;
 try {const data=await api(session?'private':'public');if(version!==refreshVersion || token!==session?.access_token)return;owner=!!session;liveWorkoutsLoaded=true;rows=data.workouts;paintSync(data.sync);publicPlans=data.plans||[];checkins=data.checkins||[];connections=data.connections||{};$('dataStatus').textContent=completed(rows).length+' completed sessions · '+(owner?'Private details visible only to you.':'Lifting sets are public. Notes stay private.');if(owner)$('loginDialog').close();}
 catch(e){if(version!==refreshVersion || token!==session?.access_token)return;liveWorkoutsLoaded=false;owner=false;rows=window.WORKOUTS||[];checkins=[];connections={};publicPlans=[];$('lastSynced').textContent='Sync time unavailable · offline history';$('dataStatus').textContent=session?'Sign-in could not unlock the owner log. '+e.message:'Showing saved historical totals. Live data is temporarily unavailable.';if(session)status('loginStatus',e.message,true);}
 render();
}
function requireOwner(action) {if(owner){action();return;} $('loginDialog').showModal();}
function openWorkout(row=null,type=null,planned=false) {
 if(row?.type==='Mobility'&&row.mobility_stretches){mobility.open(row.date);return;}
 editing=row?structuredClone(row):null; $('workoutForm').reset();$('exerciseEditor').replaceChildren();$('workoutSaveStatus').textContent='';parsedNote=null;$('notePreview').hidden=true;$('applyParsedNote').hidden=true;
 $('workoutDate').value=row?.date||localDate();$('workoutType').value=type||row?.type||'Strength';$('workoutStatus').value=planned?'planned':row?.status||'completed';$('workoutTitle').value=row?.title||'';
 $('workoutHeading').textContent=row?'Update workout.':planned?'Add a prescription.':'Log a workout.';
 for(const [id,key,scale] of [['workoutMinutes','duration_hours',60],['bikeMiles','bike_miles',1],['runMiles','run_miles',1],['swimYards','swim_yards',1],['workoutRpe','rpe',1],['averageHr','average_hr',1],['averagePower','average_power',1],['elevation','elevation_feet',1],['workoutTss','tss',1]])$(id).value=row?.[key]?Number((row[key]*scale).toFixed(3)):'';
 $('workoutNotes').value=row?.private_notes||'';$('publicProgress').checked=row?.public_progress!==false;
 for(const exercise of row?.exercises||[]) addExercise(exercise);
 if(!row && $('workoutType').value==='Strength')addExercise();$('workoutDialog').showModal();
}
function addExercise(exercise={name:'',unit:'lb',sets:[{reps:'',weight:'',rpe:'',kind:'working'}]}) {
 const div=document.createElement('div');div.className='exercise-edit';div.innerHTML=`<div class="exercise-top"><input class="exercise-name" required aria-label="Exercise name" placeholder="Exercise, e.g. squat" value="${esc(exercise.name)}"><select class="exercise-unit" required aria-label="Load unit"><option value="">Choose unit</option><option>lb</option><option>kg</option><option>bodyweight</option></select><button class="remove remove-exercise" type="button" aria-label="Remove exercise">×</button></div><div class="set-head"><span>#</span><span>Reps / sec</span><span>Load</span><span>RPE</span><span>Kind</span><span></span></div><div class="set-list"></div><button type="button" class="text-button add-set">+ Add set</button>`;
 div.querySelector('.exercise-unit').value=exercise.unit;div.querySelector('.exercise-unit').onchange=()=>{const bw=div.querySelector('.exercise-unit').value==='bodyweight';for(const input of div.querySelectorAll('.weight')){input.required=!bw;input.disabled=bw;if(bw)input.value=0;}};div.querySelector('.remove-exercise').onclick=()=>div.remove();div.querySelector('.add-set').onclick=()=>addSet(div);$('exerciseEditor').appendChild(div);
 for(const set of exercise.sets||[])addSet(div,set);
}
function addSet(div,set={reps:'',weight:'',rpe:'',kind:'working'}) {
 const el=document.createElement('div');el.className='set-edit';el.innerHTML=`<span>${div.querySelectorAll('.set-edit').length+1}</span><div class="set-measure"><select class="set-mode" aria-label="Measure set by"><option value="reps">Reps</option><option value="seconds">Seconds</option></select><input class="reps" type="number" min="1" max="1000" step="1" required aria-label="Reps" value="${esc(set.seconds??set.reps)}"></div><input class="weight" type="number" required min="0" step="0.25" aria-label="Load" value="${esc(set.weight)}"><input class="rpe" type="number" min="1" max="10" step="0.5" aria-label="Set effort" value="${esc(set.rpe??'')}"><select class="set-kind" aria-label="Set kind"><option value="working">Work</option><option value="warmup">Warm-up</option></select><button type="button" class="remove" aria-label="Remove set">×</button>`;
 const bw=div.querySelector('.exercise-unit').value==='bodyweight';el.querySelector('.weight').required=!bw;el.querySelector('.weight').disabled=bw;if(bw)el.querySelector('.weight').value=0;el.querySelector('.set-kind').value=set.kind||'working';const mode=el.querySelector('.set-mode'),amount=el.querySelector('.reps');mode.value=set.seconds!=null?'seconds':'reps';const measure=()=>{amount.max=mode.value==='seconds'?86400:1000;amount.step=mode.value==='seconds'?'any':'1';amount.setAttribute('aria-label',mode.value==='seconds'?'Seconds':'Reps');};mode.onchange=measure;measure();el.querySelector('button').onclick=()=>{el.remove();div.querySelectorAll('.set-edit').forEach((r,i)=>r.firstElementChild.textContent=i+1);};div.querySelector('.set-list').appendChild(el);
}
function readExercises() {return [...$('exerciseEditor').children].map(div=>({name:div.querySelector('.exercise-name').value.trim(),unit:div.querySelector('.exercise-unit').value,sets:[...div.querySelectorAll('.set-edit')].map(s=>({... (s.querySelector('.set-mode').value==='seconds'?{seconds:Number(s.querySelector('.reps').value)}:{reps:Number(s.querySelector('.reps').value)}),weight:Number(s.querySelector('.weight').value),rpe:s.querySelector('.rpe').value?Number(s.querySelector('.rpe').value):null,kind:s.querySelector('.set-kind').value}))}));}
$('parseNote').onclick=()=>{parsedNote=repeatNote($('workoutNotes').value,rows)||parseWorkoutNote($('workoutNotes').value);$('notePreview').hidden=false;$('applyParsedNote').hidden=!parsedNote.exercises.length;$('notePreview').innerHTML=parsedNote.exercises.length?'<h3>Proposed exercise rows</h3>'+parsedNote.exercises.map(e=>'<p><strong>'+esc(e.name)+'</strong> · '+e.sets.map(s=>(s.seconds!=null?s.seconds+' sec':s.reps+' reps')+(s.weight!==''?' at '+s.weight+' '+esc(e.unit||'(unit needed)'):' (load needed)')).join(' · ')+'</p>').join(''):'<p>No set patterns found yet. Try “squats 3 sets of 5 at 135 lb,” or enter sets below.</p>';if(parsedNote.issues.length)$('notePreview').innerHTML+='<div class="fine">'+parsedNote.issues.map(esc).join('<br>')+'</div>';if(parsedNote.unparsed.length)$('notePreview').innerHTML+='<p class="fine">Other details remain in your original note: '+esc(parsedNote.unparsed.join(' · '))+'</p>';};
$('applyParsedNote').onclick=()=>{if(!parsedNote)return;for(const div of [...$('exerciseEditor').children])if(!div.querySelector('.exercise-name').value.trim())div.remove();for(const e of parsedNote.exercises)addExercise(e);$('applyParsedNote').hidden=true;$('notePreview').innerHTML='<p class="fine">Exercise rows added below. Review loads and units, then save. Your original note is preserved.</p>';};
$('workoutForm').onsubmit=async e=>{e.preventDefault();$('saveWorkout').disabled=true;try{const workout=validateWorkout({...editing,date:$('workoutDate').value,type:$('workoutType').value,title:$('workoutTitle').value||$('workoutType').value+' workout',status:$('workoutStatus').value,duration_hours:number($('workoutMinutes').value)/60,bike_miles:number($('bikeMiles').value),run_miles:number($('runMiles').value),swim_yards:number($('swimYards').value),strength:$('workoutType').value==='Strength'||$('exerciseEditor').children.length?1:editing?.strength||0,rpe:$('workoutRpe').value?Number($('workoutRpe').value):null,average_hr:$('averageHr').value?Number($('averageHr').value):null,average_power:$('averagePower').value?Number($('averagePower').value):null,elevation_feet:$('elevation').value?Number($('elevation').value):null,tss:$('workoutTss').value?Number($('workoutTss').value):null,exercises:readExercises(),private_notes:$('workoutNotes').value,public_progress:$('publicProgress').checked,source:editing?.source||'Manual'});await api('save',{workout});await refresh();$('workoutDialog').close();}catch(e){status('workoutSaveStatus',e.message,true);}finally{$('saveWorkout').disabled=false;}};
$('addExercise').onclick=()=>addExercise();for(const id of ['addHero','addStrength','addWorkout'])$(id).onclick=()=>requireOwner(()=>openWorkout(null,id==='addStrength'?'Strength':null));$('addPlan').onclick=()=>openWorkout(null,'Strength',true);
async function signOut(){if(!auth)return;const buttons=[$('signIn'),$('signOut')];buttons.forEach(b=>b.disabled=true);try{const {error}=await auth.auth.signOut();if(error)throw error;session=null;owner=false;rows=window.WORKOUTS||[];checkins=[];connections={};publicPlans=[];render();await refresh();}catch(e){$('dataStatus').textContent='Could not sign out. '+e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
$('signIn').onclick=()=>session?signOut():$('loginDialog').showModal();$('signOut').onclick=signOut;
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!auth)return status('loginStatus','Sign-in is temporarily unavailable.',true);const button=e.submitter;button.disabled=true;try{if(!$('loginPassword').value)throw new Error('Enter your password, or choose the email-link option.');const {data,error}=await auth.auth.signInWithPassword({email:$('email').value.trim(),password:$('loginPassword').value});if(error)throw error;session=data.session;$('loginPassword').value='';await refresh();}catch(e){status('loginStatus',e.message,true);}finally{button.disabled=false;}};
$('emailLogin').onclick=async()=>{if(!auth)return;const button=$('emailLogin');button.disabled=true;try{if(!$('email').checkValidity()||!$('email').value)throw new Error('Enter your email first.');const {error}=await auth.auth.signInWithOtp({email:$('email').value.trim(),options:{emailRedirectTo:C.siteUrl,shouldCreateUser:false}});if(error)throw error;status('loginStatus','Check your email. For the Home Screen app, copy the link without opening it, then paste it below.');}catch(e){status('loginStatus',/rate limit/i.test(e.message)?'Email sending limit reached. Wait about an hour, or use your password.':e.message,true);}finally{button.disabled=false;}};
$('passwordForm').onsubmit=async e=>{e.preventDefault();if(!owner||!session)return;const button=e.submitter;button.disabled=true;try{if($('newPassword').value!==$('confirmPassword').value)throw new Error('The passwords do not match.');const {error}=await auth.auth.updateUser({password:$('newPassword').value});if(error)throw error;$('passwordForm').reset();status('passwordStatus','Password saved. Open the Home Screen app and sign in with your email and this password.');}catch(e){status('passwordStatus',e.message,true);}finally{button.disabled=false;}};
$('useMagicLink').onclick=async()=>{try{const link=new URL($('magicLink').value), params=new URLSearchParams(link.hash.slice(1));const token=link.searchParams.get('token_hash')||link.searchParams.get('token');let result;if(params.has('access_token'))result=await auth.auth.setSession({access_token:params.get('access_token'),refresh_token:params.get('refresh_token')});else if(token)result=await auth.auth.verifyOtp({token_hash:token,type:'magiclink'});else throw new Error('Paste the complete sign-in link from your email.');if(result.error)throw result.error;session=result.data.session;$('magicLink').value='';await refresh();}catch(e){status('loginStatus',e.message,true);}};
$('range').onchange=()=>{try{localStorage.setItem('fitness-journal-range',$('range').value);}catch{}visible=15;render();};$('planWeek').onchange=()=>{paintJournal(rows,publicPlans);paintReview();};$('search').oninput=()=>{visible=15;paintLog();};$('loadMore').onclick=()=>{visible+=15;paintLog();};$('exerciseSelect').onchange=paintLift;$('enduranceSport').onchange=paintEndurance;
$('addRecovery').onclick=()=>{$('recoveryForm').reset();$('recoveryDate').value=localDate();$('recoveryStatus').textContent='';$('recoveryDialog').showModal();};
$('recoveryForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const checkin={date:$('recoveryDate').value,weight_unit:$('weightUnit').value,notes:$('recoveryNotes').value};for(const [id,key]of [['sleepHours','sleep_hours'],['energy','energy'],['soreness','soreness'],['bodyWeight','weight'],['restingHr','resting_hr'],['hrv','hrv']])checkin[key]=$(id).value?Number($(id).value):null;await api('checkin',{checkin});await refresh();$('recoveryDialog').close();}catch(e){status('recoveryStatus',e.message,true);}finally{button.disabled=false;}};
async function saveConnection(body){try{await api('connections',body);await api('sync');await refresh();$('calendarUrl').value='';}catch(e){$('syncStatus').textContent=e.message;}}
$('calendarForm').onsubmit=async e=>{e.preventDefault();if(!$('calendarUrl').value)return;const b=e.submitter;b.disabled=true;await saveConnection({calendar:$('calendarUrl').value});b.disabled=false;};$('disconnectCalendar').onclick=()=>saveConnection({calendar:''});

$('csvFile').onchange=async()=>{importRows=[];$('confirmImport').hidden=true;try{const file=$('csvFile').files[0];if(!file)return;if(file.size>2000000)throw new Error('Choose a CSV smaller than 2 MB.');importRows=trainingPeaksCsv(await file.text());if(!importRows.length)throw new Error('No workouts found.');$('importPreview').innerHTML='<p class="fine">'+importRows.length+' rows ready to review. Existing matching sessions will be skipped.</p><div class="import-table">'+importRows.slice(0,12).map(r=>esc(r.date+' · '+r.type+' · '+r.title+' · '+fmt(r.duration_hours*60,1)+' min')).join('<br>')+'</div>';$('confirmImport').hidden=false;}catch(e){$('importPreview').textContent=e.message;}};
$('confirmImport').onclick=async()=>{const b=$('confirmImport');b.disabled=true;try{const result=await api('import',{workouts:importRows});await refresh();$('importPreview').textContent=result.imported+' new workouts imported.';b.hidden=true;importRows=[];}catch(e){$('importPreview').textContent=e.message;}finally{b.disabled=false;}};
for(const button of document.querySelectorAll('[data-close]')){button.innerHTML=icon('close');button.onclick=()=>$(button.dataset.close).close();}
function openNotificationWorkout(){requireOwner(()=>{const plan=rows.find(r=>r.date===localDate() && r.status==='planned' && (r.type==='Strength'||r.strength>0));openWorkout(plan?{...plan,status:'completed'}:null,'Strength');});}
const push=preview?{refresh(){}}:setupPush({api,requireOwner,openLog:()=>{notificationPending=true;if(owner){notificationPending=false;openNotificationWorkout();}else $('loginDialog').showModal();}});
const muscleMap=createMuscleMap({getRows:()=>rangeRows(),isOwner:()=>owner,getPeriodLabel:()=>$('range').selectedOptions[0].textContent});
if(preview){document.body.insertAdjacentHTML('afterbegin','<div class="preview-banner">DESIGN PREVIEW · local branch · data snapshot · saving and sign-in disabled</div>');$('signIn').disabled=true;for(const id of ['addHero','addStrength','addWorkout','mobileLog','emailLogin','useMagicLink'])$(id).disabled=true;}
render();
if(auth){const result=await auth.auth.getSession();session=result.data.session;auth.auth.onAuthStateChange((_event,newSession)=>{session=newSession;if(!session){owner=false;rows=window.WORKOUTS||[];checkins=[];connections={};render();}setTimeout(()=>refresh(),0);});}
await refresh();

function paintBest(){
 $('bestEfforts').innerHTML=bestEfforts(rows,$('bestSport').value).map(g=>'<article class="panel effort-card"><div class="eyebrow">'+esc(g.sport)+'</div><h3>'+esc(g.label)+'</h3>'+(g.records.length?'<ol>'+g.records.map(r=>'<li><div><strong>'+(g.kind==='time'?clockTime(r.effort_seconds):fmt(r[g.kind],g.kind==='swim_yards'?0:1)+' '+(g.kind==='swim_yards'?'yd':'mi'))+'</strong><span>'+pretty(r.date,{month:'short',day:'numeric',year:'numeric'})+'</span></div><p>'+esc(r.title)+(g.kind==='time'?' · '+fmt(r.effort_distance,2)+' mi'+(r.official?' · official split':' · whole-session time'):' · '+(r.type==='Race'&&r.date===SANTA_CRUZ.date?clockTime(SANTA_CRUZ[g.sport.toLowerCase()])+' official split':clockTime(r.duration_hours*3600)+(r.type==='Race'?' combined race time':'')))+'</p></li>').join('')+'</ol>':'<p class="muted">No qualifying recorded session yet.</p>')+'</article>').join('');
}
$('bestSport').onchange=paintBest;
$('logRange').onchange=()=>{const r=$('logRange').value;if(r==='custom')return;$('logFrom').value=r==='all'?'':dateStart(r);$('logTo').value=r==='all'?'':localDate();visible=15;paintLog();};
for(const id of ['logFrom','logTo'])$(id).onchange=()=>{$('logRange').value='custom';visible=15;paintLog();};
for(const id of ['logSort','logStatus'])$(id).onchange=()=>{visible=15;paintLog();};
$('showAll').onclick=()=>{visible=Infinity;paintLog();};
$('clearFilters').onclick=()=>{active='All';visible=15;for(const id of ['search','logFrom','logTo'])$(id).value='';$('logRange').value='all';$('logSort').value='newest';$('logStatus').value='completed';paintTabs();paintLog();};

$('generateRunner').onclick=()=>requireOwner(async()=>{try{const data=await api('runner_key');if(!owner)return;$('runnerKey').value=data.key;$('runnerKey').hidden=false;$('copyRunner').hidden=false;status('hostedSetupStatus','Copy this key into GitHub secret FITNESS_RUNNER_KEY. Add TP_USERNAME and TP_PASSWORD directly in GitHub, then enable the hosted check.');await refresh();}catch(e){status('hostedSetupStatus',e.message,true);}});
$('copyRunner').onclick=async()=>{try{await navigator.clipboard.writeText($('runnerKey').value);status('hostedSetupStatus','Runner key copied. Paste it into the GitHub secret, then clear your clipboard.');}catch{status('hostedSetupStatus','Select and copy the key field yourself.',true);}};
for(const [id,enabled] of [['enableHosted',true],['disableHosted',false]])$(id).onclick=()=>requireOwner(async()=>{try{await api('hosted_enable',{enabled});status('hostedSetupStatus',enabled?'Enabled. Run the hosted workflow once to verify your connection.':'Hosted check paused.');await refresh();}catch(e){status('hostedSetupStatus',e.message,true);}});

$('mobileLog').onclick=()=>requireOwner(()=>openWorkout(null,'Strength'));

function paintToday(){
 const today=localDate();$('todayDate').textContent=pretty(today,{weekday:'long',month:'long',day:'numeric'});
 const actual=completed(rows).filter(r=>r.date===today),plans=owner?rows.filter(r=>r.date===today&&r.status==='planned'):[];
 $('todaySync').textContent=owner?connections.hosted?.last_success_at?'TrainingPeaks last checked '+new Date(connections.hosted.last_success_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})+' Pacific. See connection settings for the automatic check schedule.':'No verified hosted check available. Add what you actually did.':'Sign in to see your coach’s plan and log workouts.';
 $('todayCards').innerHTML=[...actual,...plans].map(r=>`<article class="plan-card"><div class="eyebrow">${r.status==='planned'?'Prescribed':'Completed'} · ${esc(r.type)}</div><h3>${esc(r.title)}</h3><p>${r.status==='planned'?(r.planned_duration_hours?fmt(r.planned_duration_hours*60)+' min prescribed':'No prescribed duration'):esc(workoutMeta(r))}</p>${owner?`<button class="button outline today-edit" data-id="${r.id}">${r.status==='planned'?'Log actuals':'Edit actuals'}</button>`:''}</article>`).join('')||'<p class="muted">No sessions recorded for today yet. A quiet day is part of the record too.</p>';
 document.querySelectorAll('.today-edit').forEach(b=>b.onclick=()=>openWorkout({...rows.find(r=>r.id===b.dataset.id),status:'completed'}));
 $('repeatLift').hidden=!owner||!completed(rows).some(r=>(r.exercises||[]).length);
}
function paintReview(){const w=weekReview(rows,localDate(),Number($('planWeek').value));const diff=w.totals.hours-w.prior.hours;
 $('weeklyCards').innerHTML=`<div class="eyebrow">${pretty(w.start)} – ${pretty(w.end)}</div><div class="metric-pills"><span>${w.totals.sessions} completed sessions</span><span>${fmt(w.totals.hours,1)} training hours</span><span>${w.sets} working sets</span></div><p>${Number($('planWeek').value)>0?'This week hasn’t started. Planned workouts are excluded from these totals.':`${Math.abs(diff).toFixed(1)} hours ${diff>=0?'more':'less'} than the preceding week. ${Number($('planWeek').value)===0?'This week is still in progress.':''}`}</p><div class="muscle-sports">${['Swim','Bike','Run','Strength'].map(s=>`<div><span>${s}</span><strong>${w.actual.filter(r=>s==='Strength'?r.type===s||r.strength>0:r.type===s).length} sessions</strong></div>`).join('')}</div>${owner?`<p>${w.plans.length} prescriptions still without recorded actuals; ${w.skipped} explicitly skipped. Unrecorded plans are not assumed missed. Substitutions are valid.</p>`:''}`;}
function paintBenchmarks(){const sport=$('benchmarkSport').value,b=enduranceCompare(rows,sport);
 $('benchmarkCards').innerHTML=!b.latest?'<p>No measured heart-rate sessions for this sport yet.</p>':`<h3>Latest ${esc(sport.toLowerCase())}: ${pretty(b.latest.date)}</h3><p>${fmt(b.latest.average_hr)} bpm average · ${esc(workoutMeta(b.latest))}</p>${b.comparisons.length>=3?`<p><strong>${fmt(Math.abs(b.delta),1)} bpm ${b.delta>=0?'higher':'lower'}</strong> than the average of ${b.comparisons.length} earlier sessions with similar pace or bike power (within 10%) and duration (within 25%). Baseline: ${fmt(b.mean,1)} bpm.</p>`:`<p>${b.comparisons.length} comparable earlier sessions found. At least 3 are needed for a baseline; no reliable trend is shown yet.</p>`}<details><summary>Comparison sessions</summary>${b.comparisons.map(r=>`<p>${pretty(r.date)} · ${fmt(r.average_hr)} bpm · ${esc(workoutMeta(r))}</p>`).join('')||'<p>No matching measured sessions in the preceding 90 days.</p>'}</details>`;}
$('todayLog').onclick=()=>requireOwner(()=>openWorkout());$('benchmarkSport').onchange=paintBenchmarks;
$('repeatLift').onclick=()=>requireOwner(()=>{const prior=completed(rows).filter(r=>(r.exercises||[]).length).sort((a,b)=>b.date.localeCompare(a.date))[0];if(!prior)return;openWorkout();$('workoutType').value='Strength';$('workoutTitle').value='Strength workout';$('exerciseEditor').replaceChildren();for(const e of prior.exercises)addExercise(structuredClone(e));$('workoutNotes').value='Draft repeated from '+prior.date+'. Review and record actual work.';});



function paintSync(sync){const stamp=sync?.last_success_at,at=new Date(stamp);$('lastSynced').textContent=stamp&&Number.isFinite(at.getTime())?'TrainingPeaks synced '+at.toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})+(Date.now()-at.getTime()>36*3600000?' · may be out of date':''):'TrainingPeaks sync time unavailable';}
