import {icon} from './lib/icons.mjs';
import {STRETCHES,mobilityRoutine} from './lib/mobility.mjs';
import {localDate} from './lib/fitness.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createMobility(){
 $('weekAhead').insertAdjacentHTML('afterend',`<section id="mobility" class="section"><details class="panel mobility-panel"><summary><span><span class="eyebrow">AFTER TRAINING</span><h2>Tonight’s mobility.</h2><span id="mobilityTeaser" class="muted">Based on completed workouts</span></span><span aria-hidden="true">${icon('plus')}</span></summary><div class="mobility-body"><label>Workout date<input id="mobilityDate" type="date" value="${localDate()}" max="${localDate()}"></label><p id="mobilityBasis" class="fine"></p><p class="fine">Start with warm muscles: after training, or after 5–10 minutes of easy movement. Hold gently for 30 seconds per side, breathe normally, and don’t bounce. Stop if it hurts; skip or swap anything uncomfortable. These suggestions support flexibility, not injury treatment or a recovery score.</p><div id="mobilityCards" class="mobility-cards"></div><div class="mobility-timer"><div><strong id="mobilityClock">0:30</strong><span id="mobilityTimerLabel">Optional timer · one hold</span></div><button id="mobilityToggle" class="button outline" type="button">Start 30 seconds</button><button id="mobilityReset" class="text-button" type="button">Reset</button><span id="mobilityTimerStatus" role="status"></span></div><p class="fine">Repeat on the other side when indicated. Nothing here is automatically added to your workout log. <a href="https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/stretching/art-20047931" target="_blank" rel="noopener">Stretching guidance ↗</a></p></div></details></section>`);
 let rows=[],live=false,signature='',running=false,remaining=30000,deadline=0,interval=null;
 function display(){const seconds=Math.ceil(remaining/1000);$('mobilityClock').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');$('mobilityToggle').textContent=running?'Pause':remaining===0?'Start again':remaining<30000?'Resume':'Start 30 seconds';}
 function stop(){if(interval)clearInterval(interval);interval=null;running=false;}
 function reset(){stop();remaining=30000;$('mobilityTimerStatus').textContent='';display();}
 function tick(){remaining=Math.max(0,deadline-Date.now());if(!remaining){stop();$('mobilityTimerStatus').textContent='Hold finished. Relax, then switch sides if needed.';}display();}
 $('mobilityToggle').onclick=()=>{if(running){remaining=Math.max(0,deadline-Date.now());stop();display();return;}if(!remaining)remaining=30000;deadline=Date.now()+remaining;running=true;$('mobilityTimerStatus').textContent='';interval=setInterval(tick,200);display();};$('mobilityReset').onclick=reset;
 function draw(){
 const date=$('mobilityDate').value||localDate(),result=mobilityRoutine(rows,date),routine=live?result.routine:[];
 $('mobilityTeaser').textContent=routine.length?routine.length+' stretches · '+routine.reduce((n,s)=>n+s.sides*.5,0)+' minutes of holds':'Optional stretches from your workout history';
 $('mobilityBasis').textContent=!live?'Live workouts are unavailable. Refresh once the log reconnects to get a workout-based routine.':!result.actualCount?'No completed workouts recorded for '+date+'. This does not mean you took a rest day; a workout may not have synced yet.':result.unmapped?'Completed workouts are recorded, but there is not enough sport or exercise detail to tailor a routine.':date+' · Based on '+result.actualCount+' completed workout'+(result.actualCount===1?'':'s')+'. Plans are excluded. These are broad activity associations, not a diagnosis of tight muscles.';
 $('mobilityCards').innerHTML=routine.map((s,i)=>`<article class="mobility-card"><div class="eyebrow">${i+1} / ${s.sides===2?'30 SECONDS EACH SIDE':'30 SECONDS'}</div><h3>${s.name}</h3><p>${s.instructions}</p><p class="fine">Suggested after: ${esc(s.reasons.join(', '))}.</p><label>Swap stretch<select data-swap="${i}" aria-label="Swap ${s.name}">${STRETCHES.map(a=>`<option value="${a.id}" ${a.id===s.id?'selected':''}>${a.name}</option>`).join('')}</select></label></article>`).join('');
 $('mobilityCards').querySelectorAll('select').forEach(select=>select.onchange=()=>{const s=STRETCHES.find(s=>s.id===select.value),card=select.closest('article');card.querySelector('h3').textContent=s.name;card.querySelector('p').textContent=s.instructions;card.querySelector('.fine').textContent='Alternative selected by you.';card.querySelector('.eyebrow').textContent=s.sides===2?'30 SECONDS EACH SIDE':'30 SECONDS';$('mobilityTeaser').textContent='Custom routine · 30 seconds per side';reset();});
 }
 $('mobilityDate').onchange=()=>{reset();signature='';draw();};
 return {paint(nextRows,available){rows=nextRows;live=available;const next=JSON.stringify([localDate(),live,rows.filter(r=>r.date===($('mobilityDate').value||localDate()))]);if(next!==signature){signature=next;reset();draw();}}};
}
