-- Walker Wells Road to Kona: minimal live workout backend
-- Run this once in Supabase -> SQL Editor.
-- New workouts are stored here. Historical workouts stay in the website bundle.

create table if not exists public.workouts_live (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date date not null,
  type text not null,
  title text not null,
  duration_hours numeric default 0,
  bike_miles numeric default 0,
  run_miles numeric default 0,
  swim_yards numeric default 0,
  strength integer default 0,
  summary text default '',
  details text default '',
  source text default 'Website'
);

alter table public.workouts_live enable row level security;

drop policy if exists "Public can read workouts" on public.workouts_live;
create policy "Public can read workouts"
on public.workouts_live
for select
to anon
using (true);

-- Do NOT create a direct INSERT policy.
-- Inserts go through the password-checked RPC below.

create or replace function public.add_workout(
  p_password text,
  p_date date,
  p_type text,
  p_title text,
  p_duration_hours numeric default 0,
  p_bike_miles numeric default 0,
  p_run_miles numeric default 0,
  p_swim_yards numeric default 0,
  p_strength integer default 0,
  p_summary text default '',
  p_details text default ''
)
returns public.workouts_live
language plpgsql
security definer
set search_path = public
as $$
declare
  new_row public.workouts_live;
begin
  if p_password <> 'IRONMAN2027' then
    raise exception 'Invalid admin password';
  end if;

  insert into public.workouts_live (
    date, type, title, duration_hours, bike_miles, run_miles,
    swim_yards, strength, summary, details, source
  )
  values (
    p_date, p_type, p_title,
    coalesce(p_duration_hours,0),
    coalesce(p_bike_miles,0),
    coalesce(p_run_miles,0),
    coalesce(p_swim_yards,0),
    coalesce(p_strength,0),
    coalesce(p_summary,''),
    coalesce(p_details,''),
    'Website'
  )
  returning * into new_row;

  return new_row;
end;
$$;

revoke all on function public.add_workout(text,date,text,text,numeric,numeric,numeric,numeric,integer,text,text) from public;
grant execute on function public.add_workout(text,date,text,text,numeric,numeric,numeric,numeric,integer,text,text) to anon;


-- Fundraising tracker
create table if not exists public.donations_live (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date date not null,
  amount numeric not null check (amount >= 0),
  donor_name text default '',
  public_name boolean not null default true,
  note text default ''
);

alter table public.donations_live enable row level security;

drop policy if exists "Public can read donations" on public.donations_live;
create policy "Public can read donations"
on public.donations_live
for select
to anon
using (true);

-- No direct public INSERT policy. Donations must use this password-checked RPC.
create or replace function public.add_donation(
  p_password text,
  p_date date,
  p_amount numeric,
  p_donor_name text default '',
  p_public_name boolean default true,
  p_note text default ''
)
returns public.donations_live
language plpgsql
security definer
set search_path = public
as $$
declare
  new_row public.donations_live;
begin
  if p_password <> 'IRONMAN2027' then
    raise exception 'Invalid admin password';
  end if;

  if p_amount is null or p_amount < 0 then
    raise exception 'Donation amount must be zero or greater';
  end if;

  insert into public.donations_live (
    date, amount, donor_name, public_name, note
  )
  values (
    p_date,
    p_amount,
    coalesce(p_donor_name,''),
    coalesce(p_public_name,true),
    coalesce(p_note,'')
  )
  returning * into new_row;

  return new_row;
end;
$$;

revoke all on function public.add_donation(text,date,numeric,text,boolean,text) from public;
grant execute on function public.add_donation(text,date,numeric,text,boolean,text) to anon;
