-- The former campaign shared-password backend has been retired.
-- See FITNESS_SETUP.sql and supabase/functions/fitness-api/index.ts.
-- Historical workouts are preserved privately in fitness_workouts.
-- Do not restore the old public write RPCs.
