import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { totals, weekly, strengthDue, pushWindow, publicWorkout, validateWorkout, parseCalendar, trainingPeaksCsv, strengthHistory, localDate, fromIntervals } from '../lib/fitness.mjs';
const history=JSON.parse(fs.readFileSync(new URL('../workouts.json',import.meta.url)));
test('all 154 historical sessions and original totals survive',()=>{const t=totals(history);assert.equal(t.sessions,154);assert.equal(t.strength,9);assert.equal(t.hours.toFixed(1),'135.2');assert.equal(t.bike.toFixed(1),'1133.4');assert.equal(t.run.toFixed(1),'256.1');assert.equal(t.swim.toFixed(0),'71227');});
test('public projections exclude notes, sets, effort, and unexpected fields',()=>{const p=publicWorkout({date:'2026-10-06',type:'Strength',title:'Private title',details:'secret',private_notes:'secret',exercises:[{name:'Squat'}],rpe:9,weight:180,source:'Manual'});assert.equal(p.title,'Strength workout');for(const k of ['details','private_notes','exercises','rpe','weight'])assert.equal(k in p,false);});
test('planned and skipped sessions never inflate totals',()=>assert.equal(totals([{status:'planned',duration_hours:2,strength:1},{status:'skipped',duration_hours:1},{status:'completed',duration_hours:.5}]).hours,.5));
test('weekly chart includes missing weeks with zero and handles Monday boundaries',()=>{const w=weekly([{date:'2026-10-04',type:'Run',duration_hours:1},{date:'2026-10-05',type:'Strength',duration_hours:.5}],'2026-10-06',3);assert.equal(w[0].sessions,0);assert.equal(w[1].endurance,1);assert.equal(w[2].strength,.5);});
test('Los Angeles dates are correct around UTC midnight',()=>assert.equal(localDate(new Date('2026-10-07T01:00:00Z')),'2026-10-06'));
test('calendar unfolds descriptions, accepts all-day and UTC dates, ignores canceled events',()=>{const events=parseCalendar('BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nUID:a\r\nDTSTART;VALUE=DATE:20261006\r\nSUMMARY:Gym strength\r\nDESCRIPTION:Squat\\n3x5\r\n continued\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:b\r\nDTSTART:20261007T010000Z\r\nSUMMARY:Run\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:c\r\nDTSTART:20261006\r\nSTATUS:CANCELLED\r\nEND:VEVENT\r\nEND:VCALENDAR');assert.equal(events.length,2);assert.equal(events[0].type,'Strength');assert.equal(events[0].details,'Squat\n3x5continued');assert.equal(events[1].date,'2026-10-06');});
test('CSV handles quoted commas, newlines and actual metrics without substituting plans',()=>{const r=trainingPeaksCsv('WorkoutDay,WorkoutType,Title,TotalTime,TotalTimePlanned,DistanceInMeters,Description\n10/06/2026,Run,"Easy, steady",0.5,1,5000,"Line one\nLine two"')[0];assert.equal(r.duration_hours,.5);assert.equal(r.summary,'Line one\nLine two');assert.equal(r.run_miles.toFixed(2),'3.11');assert.equal(r.date,'2026-10-06');});
test('invalid dates, negative distances and fractional reps are rejected',()=>{const base={date:'2026-10-06',type:'Strength',status:'completed'};assert.throws(()=>validateWorkout({...base,date:'2026-02-30'}));assert.throws(()=>validateWorkout({...base,run_miles:-1}));assert.throws(()=>validateWorkout({...base,exercises:[{name:'Squat',unit:'lb',sets:[{reps:1.5,weight:10}]}]}));});
test('strength volume excludes warmups and never mixes lb and kg',()=>{const r=strengthHistory([{date:'2026-10-06',exercises:[{name:'Squat',unit:'lb',sets:[{kind:'warmup',weight:45,reps:10},{kind:'working',weight:135,reps:5}]}]},{date:'2026-10-07',exercises:[{name:'Squat',unit:'kg',sets:[{kind:'working',weight:60,reps:5}]}]}],'Squat');assert.equal(r[0].volume,675);assert.equal(r[0].estimatedMax,157.5);assert.equal(r[1].unit,'kg');});
test('device import converts meters and seconds; actual sport remains distinct',()=>{const r=fromIntervals({id:'1',type:'VirtualRide',start_date_local:'2026-10-06T10:00:00',moving_time:3600,distance:16093.44});assert.equal(r.type,'Bike');assert.equal(r.duration_hours,1);assert.equal(r.bike_miles,10);});

test('push check-in only targets prescribed strength without logged actuals',()=>{const planned={date:'2026-10-06',status:'planned',type:'Strength'};assert.equal(strengthDue([planned],'2026-10-06').length,1);assert.equal(strengthDue([planned,{date:'2026-10-06',type:'Strength',status:'completed',exercises:[{name:'Squat',sets:[{reps:5,weight:135}]}]}],'2026-10-06').length,0);assert.equal(strengthDue([{...planned,type:'Run'}],'2026-10-06').length,0);assert.equal(strengthDue([planned],'2026-10-07').length,0);});
test('push time is 8:30pm Pacific and follows daylight saving',()=>{assert.equal(pushWindow(new Date('2026-10-07T03:29:00Z')),false);assert.equal(pushWindow(new Date('2026-10-07T03:30:00Z')),true);assert.equal(pushWindow(new Date('2026-11-07T04:30:00Z')),true);assert.equal(pushWindow(new Date('2026-11-07T06:00:00Z')),false);});
