import test from 'node:test';import assert from 'node:assert/strict';import {parseWorkoutNote} from '../lib/note-parser.mjs';
test('conversational sentences and number words become separate exercise sets',()=>{const note='Squats, three sets of five at 135 lb. Bench, three sets of eight at 95 lb. Bodyweight pull-ups, three sets of six.';const r=parseWorkoutNote(note);assert.equal(r.exercises.length,3);assert.equal(r.exercises[0].sets.length,3);assert.equal(r.exercises[0].sets[0].weight,135);assert.equal(r.exercises[1].sets[0].reps,8);assert.equal(r.exercises[2].unit,'bodyweight');assert.equal(r.original,note);assert.equal(r.issues.length,0);});
test('load-first phrases and decimal kilogram weights are preserved',()=>{const r=parseWorkoutNote('Bench press 42.5 kg for 3 sets of 8. Squats were 5 reps at 60 kg for 2 sets.');assert.equal(r.exercises[0].sets[0].weight,42.5);assert.equal(r.exercises[0].unit,'kg');assert.equal(r.exercises[1].sets.length,2);});
test('individual sets with different loads stay distinct',()=>{const r=parseWorkoutNote('Squat: 135 lb x 5, 145 lb x 5, 155 lb x 3');assert.equal(r.exercises.length,1);assert.deepEqual(r.exercises[0].sets.map(s=>[s.weight,s.reps]),[[135,5],[145,5],[155,3]]);});
test('missing units and loads are flagged, never guessed',()=>{const r=parseWorkoutNote('Squats 3 x 5 at 135. Pull-ups 3 x 6.');assert.equal(r.exercises[0].unit,'');assert.equal(r.exercises[1].sets[0].weight,'');assert.ok(r.issues.length>=3);});
test('dumbbell per-hand basis is preserved; unspecified basis is flagged',()=>{const r=parseWorkoutNote('Dumbbell bench press 3 x 8 at 45 lb each. Dumbbell rows 3 x 10 at 40 lb.');assert.match(r.exercises[0].name,/per hand/);assert.match(r.exercises[1].name,/unspecified/);assert.ok(r.issues.some(i=>i.includes('per hand or total')));});
test('cardio and subjective notes do not become invented lifting sets',()=>{const r=parseWorkoutNote('I ran 3 miles in 30 minutes. Legs felt sore. I slept six hours.');assert.equal(r.exercises.length,0);assert.ok(r.unparsed.length);});
test('explicit overall weight unit can apply to all exercises',()=>{const r=parseWorkoutNote('All weights in pounds. Squats 3 x 5 at 135. Bench 3 x 8 at 95.');assert.equal(r.exercises[0].unit,'lb');assert.equal(r.exercises[1].unit,'lb');});

test('sets before exercise names, per-side work, and last-set variation',()=>{
 const r=parseWorkoutNote('Body weight pistol squats to the bench 10 each leg 3 sets, 3 sets of bent over rows 10 at 40lb dumbbells, 3 sets of 10 bird dogs each sides. 3 sets of half kneeling shoulder press 8 reps each side 27.5 lbs and then going up to 10 reps on last set, weighted single leg bench lateral step ups with 27.5 lbs dumbbell 3 sets of 10');
 assert.equal(r.exercises.length,5);assert.equal(r.exercises[0].unit,'bodyweight');assert.equal(r.exercises[1].sets[0].weight,40);assert.match(r.exercises[2].name,/per side/);assert.deepEqual(r.exercises[3].sets.map(s=>s.reps),[8,8,10]);assert.equal(r.exercises[4].sets[0].weight,27.5);assert.ok(r.issues.some(i=>i.includes('per hand or total')));
});
test('timed holds and omitted reps are preserved without invented rep sets',()=>{
 const note='bodyweight single leg iso glute bridges 30 seconds each side 3 sets, weighted ab crunches pull down with rope at 50 lbs 3 sets';const r=parseWorkoutNote(note);assert.equal(r.exercises.length,0);assert.equal(r.unparsed.length,2);assert.ok(r.issues.some(i=>i.includes('Timed hold')));assert.ok(r.issues.some(i=>i.includes('Reps missing')));assert.equal(r.original,note);
});
